# Generated by Django 4.1.2 on 2022-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Название')),
                ('manufacture', models.CharField(max_length=15, verbose_name='Производитель')),
                ('volume', models.IntegerField(default=5, verbose_name='Крепость')),
                ('type', models.CharField(blank=True, max_length=12, verbose_name='Тип')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
