# Generated by Django 4.1.2 on 2022-10-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_beer_title_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=17, verbose_name='Производитель')),
            ],
        ),
        migrations.AlterField(
            model_name='beer',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factory', verbose_name='Завод'),
        ),
    ]
