# Generated by Django 4.1.2 on 2022-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_factory_alter_beer_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='manufacture',
            field=models.CharField(max_length=15, verbose_name='Производитель'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
