# Generated by Django 4.1.2 on 2022-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_factory_alter_beer_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='manufacture',
            field=models.CharField(default=123, max_length=15, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
