# Generated by Django 4.1.2 on 2022-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_factory_alter_beer_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Название')),
                ('products', models.ManyToManyField(blank=True, null=True, to='main.beer')),
            ],
        ),
    ]
