# Generated by Django 4.1.2 on 2022-10-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_country_beer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='order',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
